Funder logos
DACCS-Climate/daccs-project-website pull request #10
Opened 2023-11-06 16:56 UTC by alexandercyu

- Add Funder's logos
- Add code for Funder's logos in index.html

2023-11-06 20:12 UTC, mishaschwartz requested changes
https://github.com/DACCS-Climate/daccs-project-website/pull/2#issuecomment-1796313505

2023-11-07 14:58 UTC, mishaschwartz requested changes

2023-11-07 14:58 UTC, mishaschwartz commented on templates/site/index.html
> +     <div class="col-11 d-block py-2 mx-auto border rounded cover-text-bg">
`cover-text-box` not `cover-text-bg`

2023-11-07 17:38 UTC, alexandercyu commented on templates/site/index.html
> +     <div class="col-11 d-block py-2 mx-auto border rounded cover-text-bg">
Corrected to cover-text-box

2024-03-11 20:11 UTC, mishaschwartz approved these changes

2024-03-11 20:17 UTC, merged